services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oficina-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://oficina:oficina123@db:5432/oficina?schema=public
      - JWT_SECRET=N1FSemDuULDQ2wCNLQETZQFZat5lGgqBhSSW3pgfgmt
    depends_on:
      - db
    networks:
      - oficina-network

  db:
    image: postgres:15-alpine
    container_name: oficina-db
    restart: always
    environment:
      - POSTGRES_USER=oficina
      - POSTGRES_PASSWORD=oficina123
      - POSTGRES_DB=oficina
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oficina-network

volumes:
  postgres_data:

networks:
  oficina-network:
    driver: bridge
